### ISSUE TITLE
Origin record times must be corrected

### ISSUE THREAD

**Issue by systemcrash** [happyDomain/happydomain#3]
I got HD to NXDOMAIN from my NS. 

But it displays the following, where all times are too large by 1e9. Divide by 1e9 to fix them:
e.g. should be 3600s

![times](https://user-images.githubusercontent.com/647633/220803486-b77a52ee-5ef5-4a2a-928d-0fa51ec84f90.png)

**Comment by systemcrash** [comment]
While you're there, decrease the field width to something smaller

**Comment by nemunaire** [comment]
The current SOA implementation follows the RFC 1912 which says timers in SOA are expressed in seconds:

>    Choose logical values for the timer values in the SOA record (note
>   values below must be expressed as seconds in the zone data):

We tested this with bind, knot and with a few providers exposing the SOA records: timers are reported in the correct unit in happyDomain.

Could you please check if this is something related to your domain name provider/authoritative server? (when asking with `dig`/`nslookup`/`drill` the SOA record of your domain, if it reports seconds whereas in happyDomain it exposes nanoseconds, then the issue should be fixed in the provider implementation (we rely on [dnscontrol](https://github.com/StackExchange/dnscontrol) for this), not in the web interface)

**Comment by systemcrash** [comment]
dig returns everything as expected - always has. we keep a close eye on our DNS. 

If the blame lies with the external lib, you're better positioned to sending a PR - I don't really know that code-base, or how yours uses theirs...

**Comment by systemcrash** [comment]
Another hint: if I look at the "View my zone" which presents everything which HD has, in text, all values there are correct. 

Zone Serial is correct. 

But every value which is a `time.Duration` is... wrong.

**Comment by nemunaire** [comment]
Oh weird. The fault is totally on our side, we messed up during the frontend migration, the type behavior is indeed wrong and always returns nanoseconds.

**Comment by nemunaire** [comment]
Should be fixed in 1711a4736eb607eb152670ac1fac4bcdb1ede95e.

**Comment by systemcrash** [comment]
Confirmed.

**Comment by systemcrash** [comment]
Cosmetic, but view-only looks like this (at least on firefox):

![refresh](https://user-images.githubusercontent.com/647633/221963560-aa0b25b0-5f2a-460b-85f1-2de5a49a621e.png)
